---
# Variables for jenkins-k8s-access role

kubectl_version: "v1.28.0"
jenkins_user: "jenkins"
k3s_host: "k3s"  # This should match the host in inventories.yml
k3s_vm_ip: "192.168.1.8"  # Automatically gets K3s VM IP from inventory
