apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudcart

resources:
  - ../../base

replicas:
  - name: api-gateway
    count: 3
  - name: user-service
    count: 3
  - name: product-service
    count: 3
  - name: order-service
    count: 3
  - name: notification-worker
    count: 3
  - name: frontend
    count: 3
  - name: kafka
    count: 3

images:
  - name: cloudcart/api-gateway
    newTag: v1.0.0
  - name: cloudcart/user-service
    newTag: v1.0.0
  - name: cloudcart/product-service
    newTag: v1.0.0
  - name: cloudcart/order-service
    newTag: v1.0.0
  - name: cloudcart/chaos-service
    newTag: v1.0.0
  - name: cloudcart/notification-worker
    newTag: v1.0.0
  - name: cloudcart/metrics-generator
    newTag: v1.0.0
  - name: cloudcart/frontend
    newTag: v1.0.0

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
    target:
      kind: Deployment
      labelSelector: "app in (api-gateway,user-service,product-service,order-service)"
