apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: cloudcart
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:3000']
        metrics_path: '/metrics'

      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:8001']
        metrics_path: '/metrics'

      - job_name: 'product-service'
        static_configs:
          - targets: ['product-service:8002']
        metrics_path: '/metrics'

      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:8003']
        metrics_path: '/metrics'

      - job_name: 'chaos-service'
        static_configs:
          - targets: ['chaos-service:8004']
        metrics_path: '/metrics'

      - job_name: 'notification-worker'
        static_configs:
          - targets: ['notification-worker:8005']
        metrics_path: '/metrics'

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
