apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: cloudcart
spec:
  selector:
    app: vault
  ports:
  - port: 8200
    targetPort: 8200
    name: http
  - port: 8201
    targetPort: 8201
    name: cluster
  type: ClusterIP
