apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: cloudcart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: cloudcart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: cloudcart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  namespace: cloudcart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: cloudcart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-worker
  namespace: cloudcart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-service
  namespace: cloudcart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-generator
  namespace: cloudcart
