global:
  scrape_interval: "15s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['api-gateway:3000']
  - job_name: 'user-service'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['user-service:8001']
  - job_name: 'product-service'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['product-service:8002']
  - job_name: 'order-service'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['order-service:8003']
  - job_name: 'chaos-service'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['chaos-service:8004']
  - job_name: 'notification-worker'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['notification-worker:8005']