apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cloudcart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "order-service"
        vault.hashicorp.com/agent-inject-secret-database: "cloudcart/data/database"
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "cloudcart/data/database" -}}
          export DATABASE_URL="{{ .Data.data.database_url }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-kafka: "cloudcart/data/kafka"
        vault.hashicorp.com/agent-inject-template-kafka: |
          {{- with secret "cloudcart/data/kafka" -}}
          export KAFKA_BOOTSTRAP_SERVERS="{{ .Data.data.bootstrap_servers }}"
          {{- end }}
    spec:
      serviceAccountName: order-service
      containers:
      - name: order-service
        image: anisingh28/cloudcartops-order-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: PORT
          value: "8003"
        - name: DATABASE_URL
          value: "placeholder"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:29092
        - name: PRODUCT_SERVICE_URL
          value: http://product-service:8002
        - name: SERVICE_NAME
          value: order-service
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
