apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cloudcart
type: Opaque
stringData:
  username: cloudcart
  password: cloudcart123
  database: cloudcart
  connection-string: postgresql://cloudcart:cloudcart123@postgres:5432/cloudcart?sslmode=disable
