apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: cloudcart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "api-gateway"
        vault.hashicorp.com/agent-inject-secret-config: "cloudcart/data/jwt"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "cloudcart/data/jwt" -}}
          export JWT_SECRET="{{ .Data.data.secret }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-redis: "cloudcart/data/redis"
        vault.hashicorp.com/agent-inject-template-redis: |
          {{- with secret "cloudcart/data/redis" -}}
          export REDIS_URL="{{ .Data.data.url }}"
          {{- end }}
    spec:
      serviceAccountName: api-gateway
      containers:
      - name: api-gateway
        image: anisingh28/cloudcartops-api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          value: "3000"
        - name: REDIS_URL
          value: redis://redis:6379
        - name: USER_SERVICE_URL
          value: http://user-service:8001
        - name: PRODUCT_SERVICE_URL
          value: http://product-service:8002
        - name: ORDER_SERVICE_URL
          value: http://order-service:8003
        - name: CHAOS_SERVICE_URL
          value: http://chaos-service:8004
        - name: JWT_SECRET
          value: "placeholder"
        - name: RATE_LIMIT_WINDOW
          value: "60000"
        - name: RATE_LIMIT_MAX_REQUESTS
          value: "100"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
