apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudcart

resources:
  - namespace
  - postgres
  - redis
  - kafka
  - vault
  - api-gateway
  - user-service
  - product-service
  - order-service
  - chaos-service
  - notification-worker
  - metrics-generator
  - frontend
  - prometheus
  - common/app-secrets.yaml
  - common/ingress.yaml
