apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
  namespace: cloudcart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "notification-worker"
        vault.hashicorp.com/agent-inject-secret-kafka: "cloudcart/data/kafka"
        vault.hashicorp.com/agent-inject-template-kafka: |
          {{- with secret "cloudcart/data/kafka" -}}
          export KAFKA_BOOTSTRAP_SERVERS="{{ .Data.data.bootstrap_servers }}"
          {{- end }}
    spec:
      serviceAccountName: notification-worker
      containers:
      - name: notification-worker
        image: anisingh28/cloudcartops-notification-worker:latest
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", ". /vault/secrets/kafka && exec python worker.py"]
        ports:
        - containerPort: 8005
          name: metrics
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:29092
        - name: KAFKA_GROUP_ID
          value: notification-worker-group
        - name: SERVICE_NAME
          value: notification-worker
        - name: METRICS_PORT
          value: "8005"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
