apiVersion: v1
kind: Service
metadata:
  name: notification-worker
  namespace: cloudcart
spec:
  selector:
    app: notification-worker
  ports:
  - port: 8005
    targetPort: 8005
    name: metrics
  type: ClusterIP
