name: CloudCartOps CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Health_Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1.2.0

      - name: Build and start services
        run: docker compose up -d --build

      - name: Wait for infrastructure services
        run: |
          for svc in cloudcart-postgres cloudcart-redis cloudcart-kafka; do
            echo "Waiting for $svc..."
            until [ "$(docker inspect --format='{{.State.Health.Status}}' $svc)" == "healthy" ]; do
              sleep 2
            done
            echo "$svc is healthy!"
          done

      - name: Wait for API and Frontend endpoints
        run: |
          declare -A services
          services=(
            ["api-gateway"]="http://localhost:3000/health"
            ["user-service"]="http://localhost:8001/health"
            ["product-service"]="http://localhost:8002/health"
            ["order-service"]="http://localhost:8003/health"
            ["chaos-service"]="http://localhost:8004/health"
            ["frontend"]="http://localhost:3001/"
          )

          for name in "${!services[@]}"; do
            url=${services[$name]}
            echo "Waiting for $name ($url)..."
            until curl -s -f $url; do
              sleep 2
            done
            echo "$name is ready!"
          done

      - name: Stop services
        run: docker compose down
